version: "3"
networks:
  fpts:

services:
  init_db:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: init_db
    networks:
      - fpts
    depends_on:
      - db
    environment:
      - FPTS_LOG_LEVEL=DEBUG
      - FPTS_DB_HOST=db
      - FPTS_DB_PORT=5432
      - FPTS_DB_LOGIN=top
      - FPTS_DB_PASS=secret
      - FPTS_DB_NAME=fpts
    ports:
      - 8585:8585
    command: db init

  data_db:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: data_db
    networks:
      - fpts
    depends_on:
      - db
    environment:
      - FPTS_LOG_LEVEL=DEBUG
      - FPTS_DB_HOST=db
      - FPTS_DB_PORT=5432
      - FPTS_DB_LOGIN=top
      - FPTS_DB_PASS=secret
      - FPTS_DB_NAME=fpts
    ports:
      - 8585:8585
    command: db data

  drop_db:
      build:
        context: ./
        dockerfile: Dockerfile
      container_name: drop_db
      networks:
        - fpts
      depends_on:
        - db
      environment:
        - FPTS_LOG_LEVEL=DEBUG
        - FPTS_DB_HOST=db
        - FPTS_DB_PORT=5432
        - FPTS_DB_LOGIN=top
        - FPTS_DB_PASS=secret
        - FPTS_DB_NAME=fpts
      ports:
        - 8585:8585
      command: db drop

  fpts:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fpts
    networks:
      - fpts
    depends_on:
      - db
    environment:
      - FPTS_LOG_LEVEL=DEBUG
      - FPTS_HTTP_HOST=0.0.0.0
      - FPTS_HTTP_PORT=8099
      - FPTS_DB_HOST=db
      - FPTS_DB_PORT=5432
      - FPTS_DB_NAME=fpts
      - FPTS_DB_LOGIN=top
      - FPTS_DB_PASS=secret
    ports:
      - 8099:8099

  db:
    image: postgres
    restart: always
    networks:
      - fpts
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: fpts
      POSTGRES_USER: top
      POSTGRES_PASSWORD: secret