// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi FPTS
#### FPTS API



    Schemes:
      http
    Host: some.fpts.lan
    BasePath: /
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
