// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "#### FPTS API\n",
    "title": "FPTS",
    "version": "1.0.0"
  },
  "host": "some.fpts.lan",
  "basePath": "/",
  "paths": {
    "/transaction": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "$ref": "#/parameters/source-type"
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "allOf": [
                {
                  "$ref": "#/definitions/Transaction_object"
                }
              ]
            }
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/Transaction_response_200"
          },
          "400": {
            "$ref": "#/responses/Base_response_400"
          },
          "404": {
            "$ref": "#/responses/Base_response_404"
          },
          "405": {
            "$ref": "#/responses/Base_response_405"
          },
          "500": {
            "$ref": "#/responses/Base_response_500"
          }
        }
      }
    }
  },
  "definitions": {
    "Error_400_data": {
      "allOf": [
        {
          "type": "object",
          "title": "Error_Error_400_data",
          "required": [
            "message",
            "errors"
          ],
          "properties": {
            "errors": {
              "type": "array",
              "items": {}
            },
            "message": {
              "type": "string",
              "example": "Validation error"
            }
          }
        }
      ]
    },
    "Error_404_data": {
      "allOf": [
        {
          "type": "object",
          "title": "Error_Error_404_data",
          "required": [
            "message",
            "errors"
          ],
          "properties": {
            "errors": {
              "type": "array",
              "items": {}
            },
            "message": {
              "type": "string",
              "example": "Not found"
            }
          }
        }
      ]
    },
    "Error_405_data": {
      "allOf": [
        {
          "type": "object",
          "title": "Error_Error_405_data",
          "properties": {
            "errors": {},
            "message": {
              "type": "string",
              "example": "Method ${METHOD} not allowed"
            }
          }
        }
      ]
    },
    "Error_500_data": {
      "allOf": [
        {
          "type": "object",
          "title": "Error_500_data",
          "required": [
            "message",
            "errors"
          ],
          "properties": {
            "errors": {},
            "message": {
              "type": "string",
              "example": "Internal server error"
            }
          }
        }
      ]
    },
    "Success_data": {
      "description": "Done",
      "type": "object",
      "title": "Success_data",
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string",
          "example": "SUCCESS"
        }
      }
    },
    "Transaction_object": {
      "title": "Transaction_object",
      "required": [
        "transactionID",
        "state",
        "amount"
      ],
      "properties": {
        "amount": {
          "description": "amount",
          "type": "string",
          "example": "10.15"
        },
        "state": {
          "description": "state",
          "type": "string",
          "example": "win"
        },
        "transactionID": {
          "description": "transactionID",
          "type": "string",
          "example": "a3190bfc-593c-49c4-95b1-82e91ec3d022"
        }
      }
    }
  },
  "parameters": {
    "source-type": {
      "type": "string",
      "description": "source-type value",
      "name": "Source-Type",
      "in": "header",
      "required": true
    }
  },
  "responses": {
    "Base_response_400": {
      "description": "Invalid transactionID",
      "schema": {
        "allOf": [
          {
            "$ref": "#/definitions/Error_400_data"
          },
          {
            "type": "object",
            "required": [
              "message",
              "errors"
            ],
            "properties": {
              "errors": {
                "type": "object",
                "properties": {
                  "transactionID": {
                    "type": "string"
                  }
                }
              },
              "message": {
                "type": "string",
                "example": "TransactionID already exist"
              }
            }
          }
        ]
      }
    },
    "Base_response_404": {
      "description": "Not found",
      "schema": {
        "allOf": [
          {
            "$ref": "#/definitions/Error_404_data"
          }
        ]
      }
    },
    "Base_response_405": {
      "description": "Invalid Method",
      "schema": {
        "allOf": [
          {
            "$ref": "#/definitions/Error_405_data"
          }
        ]
      }
    },
    "Base_response_500": {
      "description": "Internal server error",
      "schema": {
        "allOf": [
          {
            "$ref": "#/definitions/Error_500_data"
          }
        ]
      }
    },
    "Transaction_response_200": {
      "description": "Transaction result",
      "schema": {
        "allOf": [
          {
            "$ref": "#/definitions/Success_data"
          },
          {
            "type": "object",
            "required": [
              "data"
            ],
            "properties": {
              "data": {
                "type": "object",
                "allOf": [
                  {
                    "$ref": "#/definitions/Transaction_object"
                  }
                ]
              }
            }
          }
        ]
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "#### FPTS API\n",
    "title": "FPTS",
    "version": "1.0.0"
  },
  "host": "some.fpts.lan",
  "basePath": "/",
  "paths": {
    "/transaction": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "type": "string",
            "description": "source-type value",
            "name": "Source-Type",
            "in": "header",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/postTransactionParamsBody"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Transaction result",
            "schema": {
              "$ref": "#/definitions/postTransactionOKBody"
            }
          },
          "400": {
            "description": "Invalid transactionID",
            "schema": {
              "$ref": "#/definitions/postTransactionBadRequestBody"
            }
          },
          "404": {
            "description": "Not found",
            "schema": {
              "$ref": "#/definitions/postTransactionNotFoundBody"
            }
          },
          "405": {
            "description": "Invalid Method",
            "schema": {
              "$ref": "#/definitions/postTransactionMethodNotAllowedBody"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/postTransactionInternalServerErrorBody"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error_400_data": {
      "allOf": [
        {
          "$ref": "#/definitions/error400DataAllOf0"
        }
      ]
    },
    "Error_404_data": {
      "allOf": [
        {
          "$ref": "#/definitions/error404DataAllOf0"
        }
      ]
    },
    "Error_405_data": {
      "allOf": [
        {
          "$ref": "#/definitions/error405DataAllOf0"
        }
      ]
    },
    "Error_500_data": {
      "allOf": [
        {
          "$ref": "#/definitions/error500DataAllOf0"
        }
      ]
    },
    "Success_data": {
      "description": "Done",
      "type": "object",
      "title": "Success_data",
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string",
          "example": "SUCCESS"
        }
      }
    },
    "Transaction_object": {
      "title": "Transaction_object",
      "required": [
        "transactionID",
        "state",
        "amount"
      ],
      "properties": {
        "amount": {
          "description": "amount",
          "type": "string",
          "example": "10.15"
        },
        "state": {
          "description": "state",
          "type": "string",
          "example": "win"
        },
        "transactionID": {
          "description": "transactionID",
          "type": "string",
          "example": "a3190bfc-593c-49c4-95b1-82e91ec3d022"
        }
      }
    },
    "error400DataAllOf0": {
      "type": "object",
      "title": "Error_Error_400_data",
      "required": [
        "message",
        "errors"
      ],
      "properties": {
        "errors": {
          "type": "array",
          "items": {}
        },
        "message": {
          "type": "string",
          "example": "Validation error"
        }
      },
      "x-go-gen-location": "models"
    },
    "error404DataAllOf0": {
      "type": "object",
      "title": "Error_Error_404_data",
      "required": [
        "message",
        "errors"
      ],
      "properties": {
        "errors": {
          "type": "array",
          "items": {}
        },
        "message": {
          "type": "string",
          "example": "Not found"
        }
      },
      "x-go-gen-location": "models"
    },
    "error405DataAllOf0": {
      "type": "object",
      "title": "Error_Error_405_data",
      "properties": {
        "errors": {},
        "message": {
          "type": "string",
          "example": "Method ${METHOD} not allowed"
        }
      },
      "x-go-gen-location": "models"
    },
    "error500DataAllOf0": {
      "type": "object",
      "title": "Error_500_data",
      "required": [
        "message",
        "errors"
      ],
      "properties": {
        "errors": {},
        "message": {
          "type": "string",
          "example": "Internal server error"
        }
      },
      "x-go-gen-location": "models"
    },
    "postTransactionBadRequestBody": {
      "allOf": [
        {
          "$ref": "#/definitions/Error_400_data"
        },
        {
          "$ref": "#/definitions/postTransactionBadRequestBodyAllOf1"
        }
      ],
      "x-go-gen-location": "operations"
    },
    "postTransactionBadRequestBodyAllOf1": {
      "type": "object",
      "required": [
        "message",
        "errors"
      ],
      "properties": {
        "errors": {
          "$ref": "#/definitions/postTransactionBadRequestBodyAllOf1Errors"
        },
        "message": {
          "type": "string",
          "example": "TransactionID already exist"
        }
      },
      "x-go-gen-location": "operations"
    },
    "postTransactionBadRequestBodyAllOf1Errors": {
      "type": "object",
      "properties": {
        "transactionID": {
          "type": "string"
        }
      },
      "x-go-gen-location": "operations"
    },
    "postTransactionInternalServerErrorBody": {
      "allOf": [
        {
          "$ref": "#/definitions/Error_500_data"
        }
      ],
      "x-go-gen-location": "operations"
    },
    "postTransactionMethodNotAllowedBody": {
      "allOf": [
        {
          "$ref": "#/definitions/Error_405_data"
        }
      ],
      "x-go-gen-location": "operations"
    },
    "postTransactionNotFoundBody": {
      "allOf": [
        {
          "$ref": "#/definitions/Error_404_data"
        }
      ],
      "x-go-gen-location": "operations"
    },
    "postTransactionOKBody": {
      "allOf": [
        {
          "$ref": "#/definitions/Success_data"
        },
        {
          "$ref": "#/definitions/postTransactionOKBodyAllOf1"
        }
      ],
      "x-go-gen-location": "operations"
    },
    "postTransactionOKBodyAllOf1": {
      "type": "object",
      "required": [
        "data"
      ],
      "properties": {
        "data": {
          "$ref": "#/definitions/postTransactionOKBodyAllOf1Data"
        }
      },
      "x-go-gen-location": "operations"
    },
    "postTransactionOKBodyAllOf1Data": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/Transaction_object"
        }
      ],
      "x-go-gen-location": "operations"
    },
    "postTransactionParamsBody": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/Transaction_object"
        }
      ],
      "x-go-gen-location": "operations"
    }
  },
  "parameters": {
    "source-type": {
      "type": "string",
      "description": "source-type value",
      "name": "Source-Type",
      "in": "header",
      "required": true
    }
  },
  "responses": {
    "Base_response_400": {
      "description": "Invalid transactionID",
      "schema": {
        "allOf": [
          {
            "$ref": "#/definitions/Error_400_data"
          },
          {
            "type": "object",
            "required": [
              "message",
              "errors"
            ],
            "properties": {
              "errors": {
                "type": "object",
                "properties": {
                  "transactionID": {
                    "type": "string"
                  }
                }
              },
              "message": {
                "type": "string",
                "example": "TransactionID already exist"
              }
            }
          }
        ]
      }
    },
    "Base_response_404": {
      "description": "Not found",
      "schema": {
        "allOf": [
          {
            "$ref": "#/definitions/Error_404_data"
          }
        ]
      }
    },
    "Base_response_405": {
      "description": "Invalid Method",
      "schema": {
        "allOf": [
          {
            "$ref": "#/definitions/Error_405_data"
          }
        ]
      }
    },
    "Base_response_500": {
      "description": "Internal server error",
      "schema": {
        "allOf": [
          {
            "$ref": "#/definitions/Error_500_data"
          }
        ]
      }
    },
    "Transaction_response_200": {
      "description": "Transaction result",
      "schema": {
        "allOf": [
          {
            "$ref": "#/definitions/Success_data"
          },
          {
            "type": "object",
            "required": [
              "data"
            ],
            "properties": {
              "data": {
                "type": "object",
                "allOf": [
                  {
                    "$ref": "#/definitions/Transaction_object"
                  }
                ]
              }
            }
          }
        ]
      }
    }
  }
}`))
}
