swagger: '2.0'
info:
  version: "1.0.0"
  title: FPTS
  description: |
    #### FPTS API
schemes:
  - http
host: "some.fpts.lan"
basePath: /

parameters:
  Source-Type:
    name: Source-Type
    in: header
    description: "Source-Type"
    type: string
    required: true

paths:
  /transaction:
    post:
      parameters:
        - $ref: "#/parameters/Source-Type"
        - name: body
          in: body
          required: true
          schema:
            type: object
            allOf:
              - $ref: "#/definitions/Transaction_object"
      produces:
        - application/json
      consumes:
        - application/json
      responses:
        200:
          $ref: "#/responses/Transaction_response_200"
        400:
          $ref: "#/responses/Base_response_400"
        404:
          $ref: "#/responses/Base_response_404"
        405:
          $ref: "#/responses/Base_response_405"
        500:
          $ref: "#/responses/Base_response_500"


responses:
  Transaction_response_200:
    description: "Transaction result"
    schema:
      allOf:
        - $ref: "#/definitions/Success_data"
        - type: object
          properties:
            data:
              type: object
              allOf:
                - $ref: "#/definitions/Response_object"
          required:
            - data

  Base_response_400:
    description: "Invalid transactionID"
    schema:
      allOf:
        - $ref: "#/definitions/Error_data"

  Base_response_404:
    description: "Not found"
    schema:
      allOf:
        - $ref: "#/definitions/Error_data"

  Base_response_405:
    description: "Invalid Method"
    schema:
      allOf:
        - $ref: "#/definitions/Error_data"

  Base_response_500:
    description: "Internal server error"
    schema:
      allOf:
        - $ref: "#/definitions/Error_data"

definitions:
  Success_data:
    allOf:
      - type: object
        title: Success_data
        properties:
          message:
            type: string
            example: "SUCCESS"
        required:
          - message
          - errors

  Error_data:
    allOf:
      - type: object
        properties:
          message:
            type: string
            example: "error name"
          errors:
            type: string
            example: "error reason"
        required:
          - message
          - errors


  Transaction_object:
    title: Transaction_object
    properties:
      userGUID:
        type: string
        description: "userGUID"
        example: "05b342e7-e60f-43b0-bbd4-2c822df3e637"
        format: uuid
      transactionID:
        type: string
        description: "transactionID"
        example: "a3190bfc-593c-49c4-95b1-82e91ec3d022"
        format: uuid
      state:
        type: string
        description: "state"
        example: "win"
      amount:
        type: string
        description: "amount"
        example: "10.15"
    required:
      - userGUID
      - transactionID
      - state
      - amount

  Response_object:
    title: Response_object
    properties:
      userGUID:
        type: string
        description: "userGUID"
        example: "05b342e7-e60f-43b0-bbd4-2c822df3e637"
        format: uuid
      state:
        type: string
        description: "state"
        example: "win"
      amount:
        type: string
        description: "amount"
        example: "10.15"
      wallet:
        type: string
        description: "wallet info"
        example: "100.15"
    required:
      - userGUID