// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Error404Data error 404 data
// swagger:model Error_404_data
type Error404Data struct {
	Error404DataAllOf0
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *Error404Data) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 Error404DataAllOf0
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.Error404DataAllOf0 = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m Error404Data) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.Error404DataAllOf0)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this error 404 data
func (m *Error404Data) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with Error404DataAllOf0
	if err := m.Error404DataAllOf0.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Error404Data) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Error404Data) UnmarshalBinary(b []byte) error {
	var res Error404Data
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
