// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PostTransactionInternalServerErrorBody post transaction internal server error body
// swagger:model postTransactionInternalServerErrorBody
type PostTransactionInternalServerErrorBody struct {
	Error500Data
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *PostTransactionInternalServerErrorBody) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 Error500Data
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.Error500Data = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m PostTransactionInternalServerErrorBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.Error500Data)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this post transaction internal server error body
func (m *PostTransactionInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with Error500Data
	if err := m.Error500Data.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *PostTransactionInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostTransactionInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res PostTransactionInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
