// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PostTransactionOKBodyAllOf1Data post transaction o k body all of1 data
// swagger:model postTransactionOKBodyAllOf1Data
type PostTransactionOKBodyAllOf1Data struct {
	ResponseObject
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *PostTransactionOKBodyAllOf1Data) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 ResponseObject
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.ResponseObject = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m PostTransactionOKBodyAllOf1Data) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.ResponseObject)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this post transaction o k body all of1 data
func (m *PostTransactionOKBodyAllOf1Data) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with ResponseObject
	if err := m.ResponseObject.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *PostTransactionOKBodyAllOf1Data) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostTransactionOKBodyAllOf1Data) UnmarshalBinary(b []byte) error {
	var res PostTransactionOKBodyAllOf1Data
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
