// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ResponseObject Response_object
// swagger:model Response_object
type ResponseObject struct {

	// amount
	Amount string `json:"amount,omitempty"`

	// state
	State string `json:"state,omitempty"`

	// userGUID
	// Required: true
	// Format: uuid
	UserGUID *strfmt.UUID `json:"userGUID"`

	// wallet info
	Wallet string `json:"wallet,omitempty"`
}

// Validate validates this response object
func (m *ResponseObject) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateUserGUID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResponseObject) validateUserGUID(formats strfmt.Registry) error {

	if err := validate.Required("userGUID", "body", m.UserGUID); err != nil {
		return err
	}

	if err := validate.FormatOf("userGUID", "body", "uuid", m.UserGUID.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ResponseObject) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponseObject) UnmarshalBinary(b []byte) error {
	var res ResponseObject
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
